site_name: Prácticas en AWS para ASIR
use_directory_urls: false

nav:
  - "Inicio": "index.md"
  - "Lanzamiento del Laboratorio": "practica00.md"
  - "Creación de MV": "practica01.md"
  - "Redes Virtuales":
      - "Redes Virtuales": "practica03.md"
      - "FAQ": "faqredes.md"
  - "Bases de Datos": 
      - "Base de datos pública": "practica04.md"
      - "Base de datos privada": "practica05.md"

theme:
    language: es
    name: "material"
    favicon: "images/cloud-computing.png"
    palette:
        - scheme: default
          primary: indigo
          accent: "light blue"
          toggle:
            icon: material/toggle-switch-off-outline
            name: Cambiar a modo noche
        - scheme: slate 
          primary: indigo
          accent: "light blue"
          toggle:
            icon: material/toggle-switch
            name: Cambiar a modo día
    font:
        text: Roboto
        code: Roboto Mono
    logo: "images/cloud-computing.png"
    features:
        - header.autohide
        - navigation.top
        - navigation.tracking
        - navigation.footer
        - navigation.indexes
        - content.code.annotate
        - announce.dismiss
        - toc.follow
        - content.code.copy

extra_css:
  - css/extra.css

extra:
  search:
    language: "es"

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
